name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - main
    paths:
      - 'src/**'
      - 'package.json'
      - 'svelte.config.js'
      - '.github/workflows/deploy.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps --prefer-online

      - name: Clean build directory
        run: rm -rf build
      
      - name: Build the site
        env:
          BASE_PATH: '/dsa-visualizer'
          NODE_ENV: production
        run: npm run build

      - name: Verify build output
        run: test -d build || (echo "Build directory missing" && exit 1)
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
       